In [2]:
import numpy as np

#### 1. Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

In [3]:
## Numpy dizileri tek boyutlu olursa Vektör, çok boyutlu olursa Matris denir.

***

#### 2. 10 elemanli bir listeden NumPy Array’i olusturunuz.

In [4]:
np.array([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

***

#### 3. Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [5]:
np.zeros((10,10), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

***

#### 4. Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

In [6]:
np.ones((10,10), dtype = float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

***

#### 5. Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [7]:
np.full((10,10), 9)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

***

#### 6. 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.


In [8]:
np.arange(5,25, 3)

array([ 5,  8, 11, 14, 17, 20, 23])

---

#### 7. -1 ile 1 arasinda 30 adet Array olusturunuz.


In [9]:
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

***

#### 8. 0 ile 30 arasinda 5x6’lik bir matris olusturun.


In [10]:
np.random.randint(0, 10, (5,6))

array([[2, 1, 9, 4, 9, 7],
       [8, 3, 2, 2, 1, 4],
       [1, 9, 7, 3, 1, 0],
       [0, 0, 1, 2, 7, 9],
       [4, 2, 0, 8, 8, 1]])

***

#### 9. Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.


In [11]:
np.eye(10,dtype="int") 

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

***

#### 10. 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin; • eleman sayisini • boyut bilgisini/sayisini • satir X sutun bilgisini • veri tipini numpy metodlariyla yazdiriniz.


In [12]:
a=np.random.randint(0, 10, (5,10))
a

array([[2, 5, 9, 7, 2, 8, 1, 0, 4, 0],
       [6, 1, 4, 5, 3, 3, 5, 6, 6, 9],
       [9, 0, 9, 3, 3, 1, 1, 5, 1, 8],
       [7, 2, 8, 6, 0, 5, 2, 7, 2, 7],
       [3, 3, 8, 5, 6, 8, 5, 6, 1, 1]])

In [13]:
a.size

50

In [14]:
a.ndim

2

In [15]:
a.shape

(5, 10)

In [16]:
a.dtype

dtype('int32')

***

#### 11 .0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

In [17]:
b = np.random.randint(0, 10, (3,4,7))
b

array([[[7, 3, 7, 3, 3, 8, 3],
        [9, 9, 2, 5, 8, 2, 3],
        [4, 1, 9, 5, 6, 1, 2],
        [7, 0, 8, 7, 7, 2, 3]],

       [[6, 5, 2, 1, 3, 0, 2],
        [2, 1, 9, 0, 0, 2, 4],
        [8, 0, 1, 8, 6, 8, 0],
        [2, 7, 7, 0, 3, 2, 0]],

       [[2, 5, 6, 9, 9, 3, 3],
        [5, 0, 8, 2, 5, 1, 3],
        [4, 7, 9, 8, 2, 0, 1],
        [9, 7, 5, 0, 3, 5, 6]]])

***

#### 12. Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [18]:
a = np.array([1,2,3,5,6,7,8,9,10]) 
print(a)
print("----------------------------")
print("vektor boyut :",a.ndim)
print("----------------")
b = a.reshape((3,3))
print(b)
print("------------")
print("matrix boyut :",b.ndim)

[ 1  2  3  5  6  7  8  9 10]
----------------------------
vektor boyut : 1
----------------
[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]
------------
matrix boyut : 2


***

#### 13. 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
d = np.array([10,11,12])
np.concatenate([a, b , c, d])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

***

#### 14. 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

In [20]:
a = np.array([[10],
              [11]])

b = np.array([[9, 8, 7],
              [6, 5, 4]])

c = np.hstack([a, b])
c


array([[10,  9,  8,  7],
       [11,  6,  5,  4]])

---

#### 15. Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

In [21]:
# Numpy’da boyutlar axis olarak isimlendirilir, axis hangi bazda işlem yapacağınızı açıklar, 
# axis = 0 ise satir bazında, axis = 1 ise sütun bazında işlem yapacağınız anlamına gelir.

***

#### 16. Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.

In [22]:
a = np.arange(3)
b = np.arange(9).reshape(3,3)
c = np.vstack([a, b])
c


array([[0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

***

#### 17. 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 5 ayri array olusturunuz.

In [23]:
x = np.arange(10)

In [24]:
np.split(x, [1,3,5,7])

[array([0]), array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8, 9])]

***

#### 18. Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [25]:
a_random = np.random.randint(10, size=8)
a_random

array([7, 3, 5, 3, 2, 1, 1, 0])

siralama

In [26]:
np.sort(a_random) 

array([0, 1, 1, 2, 3, 3, 5, 7])

siralamadan sonra hangi elemanin hangi indexte oldugu

In [27]:
np.argsort(a_random) 

array([7, 5, 6, 4, 1, 3, 2, 0], dtype=int64)

***

#### 19. 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [28]:
b_random=np.random.randint(50, size = 20)
b_random

array([ 1, 24, 20, 38, 25,  5, 27, 19, 18, 44, 25, 49, 23, 28, 38,  0, 39,
       24,  0,  0])

vektorun 3. 5. ve 7. elemanlari

In [29]:
eleman_3 = b_random[3]
eleman_5 = b_random[5]
eleman_7 = b_random[7]
print("3.Eleman", eleman_3)
print("-----------")
print("5.Eleman", eleman_5)
print("-----------")
print("7.Eleman", eleman_7)


3.Eleman 38
-----------
5.Eleman 5
-----------
7.Eleman 19


***

#### 20. 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.

In [30]:
c_random = np.random.randint(55, size=10)
c_random


array([29,  2, 36, 27, 15,  9, 38, 12, 34,  0])

4.elemanini 6 sayiyla degistirme

In [31]:
c_random[3] = 6
c_random

array([29,  2, 36,  6, 15,  9, 38, 12, 34,  0])

***

#### 21. “Diagonal Matrix” ve “Trace of Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

In [32]:
# Diagonal Matrix   : Köşegen dışı tüm girişlerin sıfır olduğu bir matristir. 
# Trace Matrix      : Bir kare matrisin ana köşegenindeki elemanların toplamıdir.

***

#### 22. 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [33]:
a = np.random.randint(0, 50, (5, 5))  # oncelikle bir matrix olusturduk
print(a)
print("--------------------------------")
print("diagonal_matrix", a.diagonal())


[[21  6 35  0  9]
 [ 1 20 44 32 18]
 [36 35 40 11 13]
 [ 7 17  5 43  5]
 [ 2 41 10 34 46]]
--------------------------------
diagonal_matrix [21 20 40 43 46]


***

##### 23. 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [34]:
a = np.arange(10, 20)
a[3:]


array([13, 14, 15, 16, 17, 18, 19])

***

##### 24. 10X10 luk bir matris olusturunuz ve ; • 3.satir ve 5.sutuna ulasiniz. • 5.sutunun tum satirlarina ulasiniz. • Tum sutunlarin 2.satirlarina ulasiniz. • tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. • satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. • satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. • sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz. • 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

In [35]:
a = np.random.randint(50, size=(10, 10))
print(a)


[[26 10  9 16 36 39  3 12  9 24]
 [ 3 29 24 17 22 27 17 19 24 43]
 [43 49 38 37 30  2 19 18 11 17]
 [14 46  8 45 49 14 12  7 19 16]
 [44 22  3  5 30 13 24 21  2 10]
 [14  3  5 36 16 39 39 30 41 26]
 [29 47  2 39 36 26 27 16  7 42]
 [ 7  4  2  5 28 46 37 26  2  3]
 [ 9 36 25 24 27 21 21  2 14 18]
 [15 11 12 44  0 43 15 36 13 32]]


3.Satirin 5.Sutunu

In [36]:
a[3:,5]

array([14, 13, 39, 26, 46, 21, 43])

5.Sutunun Tum Satirlarina

In [37]:
a[:,5]


array([39, 27,  2, 14, 13, 39, 26, 46, 21, 43])

Tum Sutunlarin 2.Satiri

In [38]:
a[2,:]

array([43, 49, 38, 37, 30,  2, 19, 18, 11, 17])

Tum Sutunlarin 2 ile 7 arasi Satirlari

In [39]:
a[2:7,:]

array([[43, 49, 38, 37, 30,  2, 19, 18, 11, 17],
       [14, 46,  8, 45, 49, 14, 12,  7, 19, 16],
       [44, 22,  3,  5, 30, 13, 24, 21,  2, 10],
       [14,  3,  5, 36, 16, 39, 39, 30, 41, 26],
       [29, 47,  2, 39, 36, 26, 27, 16,  7, 42]])

Satir 2 den 5 e-sutun 3 den 7 e

In [40]:
a[2:5,3:7]

array([[37, 30,  2, 19],
       [45, 49, 14, 12],
       [ 5, 30, 13, 24]])

Satir 5 den sona e-sutun 0 dan 4 e

In [41]:
a[5:,:4]


array([[14,  3,  5, 36],
       [29, 47,  2, 39],
       [ 7,  4,  2,  5],
       [ 9, 36, 25, 24],
       [15, 11, 12, 44]])

3-6-9 sutunlarin tum satiri

In [42]:
a[0:,[3,6,9]]


array([[16,  3, 24],
       [17, 17, 43],
       [37, 19, 17],
       [45, 12, 16],
       [ 5, 24, 10],
       [36, 39, 26],
       [39, 27, 42],
       [ 5, 37,  3],
       [24, 21, 18],
       [44, 15, 32]])

In [43]:
a[5, 5] = 1985
print(a)


[[  26   10    9   16   36   39    3   12    9   24]
 [   3   29   24   17   22   27   17   19   24   43]
 [  43   49   38   37   30    2   19   18   11   17]
 [  14   46    8   45   49   14   12    7   19   16]
 [  44   22    3    5   30   13   24   21    2   10]
 [  14    3    5   36   16 1985   39   30   41   26]
 [  29   47    2   39   36   26   27   16    7   42]
 [   7    4    2    5   28   46   37   26    2    3]
 [   9   36   25   24   27   21   21    2   14   18]
 [  15   11   12   44    0   43   15   36   13   32]]


***

#### 25. 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin; • 20 den buyuk olan kac deger var. • 30’dan kucuk kac deger var • icerisinde 33 gecen kac deger var • olusturulan arrayin tum elemanlarini 5 ile carpin. • olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

In [44]:
a = np.arange(0, 50, 5)
print("array                                    :", a)
print("---------------------------------------------------------------------------")
print("20 den Buyuk Degerler                    :", np.sum(a > 20))
print("---------------------------------------------")
print("30 dan Kucuk Degerler                    :", np.sum(a < 30))
print("---------------------------------------------")
print("33 Olan Degerler                         :", np.sum((a > 33) & (a < 33)))
print("---------------------------------------------")
print("Tum Elemanlarin 5 ile Carpimi            :", a * 5)
print("------------------------------------------------------------------------------------")
print("Tum Elemanlarin 2 ile Bolumunden Kalan   :", a % 2)
print("----------------------------------------------------------------")


array                                    : [ 0  5 10 15 20 25 30 35 40 45]
---------------------------------------------------------------------------
20 den Buyuk Degerler                    : 5
---------------------------------------------
30 dan Kucuk Degerler                    : 6
---------------------------------------------
33 Olan Degerler                         : 0
---------------------------------------------
Tum Elemanlarin 5 ile Carpimi            : [  0  25  50  75 100 125 150 175 200 225]
------------------------------------------------------------------------------------
Tum Elemanlarin 2 ile Bolumunden Kalan   : [0 1 0 1 0 1 0 1 0 1]
----------------------------------------------------------------


***

#### 26. 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve; • orlamasini aliniz. • standart sapmasini aliniz. • varyansini aliniz. • median’ini aliniz. • en kucuk degeri bulunuz. • en buyuk degeri bulunuz. Master odev ; Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.

In [45]:
a = np.linspace(0, 1, 50)
print(a)
print("-------------------------------------------------------------------")
print("Ortalamasi           :", np.mean(a))
print("-----------------------------------------")
print("Standart Sapma       :", np.std(a))
print("-----------------------------------------")
print("Varyans              :", np.var(a))
print("-----------------------------------------")
print("Median               :", np.median(a))
print("---------------------------")
print("En Kucuk Deger       :", np.min(a))
print("---------------------------")
print("En Buyuk Deger       :", np.max(a))
print("---------------------------")


[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
-------------------------------------------------------------------
Ortalamasi           : 0.5
-----------------------------------------
Standart Sapma       : 0.2945075446869757
-----------------------------------------
Varyans              : 0.086734693877551
-----------------------------------------
Median               : 0.5
---------------------------
En Kucuk Deger       : 0.0
---------------------------
En Buyuk Deger       : 1.0


***

##### Master odev ; Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.

In [52]:
import time

start_time = time.time()
count = 0

while True:
    count += 1
    mat_1 = np.random.rand(8, 8)
    # print('mat1', mat_1 )
    mat_2 = np.random.rand(8, 8)
    # print('mat2', mat_2 )
    diago = np.diag(mat_1 - mat_2)
    #print('diago', diago)

    if (np.all((diago > -0.1) & (diago < 0.1)))==True:
        t2=time.time()
        break    

finish_time = time.time()
print('Elapsed Time :', finish_time - start_time )
print('Loop Number  :', count)
print('Matris       :', mat_1 - mat_2)

Elapsed Time : 3.650864601135254
-----------------------------------------
Loop Number  : 334207
Matris       : [[-0.08736076 -0.58240654 -0.59757226 -0.21514235  0.43237035 -0.08158674
   0.33603506 -0.29302749]
 [-0.23559651 -0.04452079  0.32186111  0.68401024 -0.53941606 -0.6639104
  -0.13037398  0.0070479 ]
 [ 0.23125886  0.26756808  0.04738287 -0.5831596  -0.06051403 -0.03965182
   0.45250635 -0.66589686]
 [-0.26200103 -0.71667061  0.25165235 -0.08531553  0.20537022 -0.0842437
   0.02350919  0.1387915 ]
 [-0.50228276  0.49028936 -0.14226718  0.72682138 -0.05344641 -0.26652763
   0.94418333  0.3201581 ]
 [ 0.28118944  0.00653971 -0.48433945 -0.00894165 -0.46087746  0.09503104
   0.30638344 -0.24541352]
 [ 0.64799159  0.11053174  0.23676439 -0.48628782 -0.03407671  0.14450295
  -0.01987233  0.45058967]
 [-0.08082792  0.14234465  0.13455291  0.08543473 -0.16071704  0.16111115
   0.07408509  0.04365349]]
